dbfilename redis_queue.rdb
dir /home/user/apparel-erp/config/pids
pidfile /home/user/apparel-erp/config/pids/redis_queue.pid
bind 127.0.0.1
port 11004

aclfile /home/user/apparel-erp/config/redis_queue.acl
