dbfilename redis_cache.rdb
dir /home/user/apparel-erp/config/pids
pidfile /home/user/apparel-erp/config/pids/redis_cache.pid
bind 127.0.0.1
port 13004
maxmemory 784mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/user/apparel-erp/config/redis_cache.acl
